import { StyleSheet, Dimensions } from 'react-native';
import { C, F } from '../constants/colors';

const { width: SW } = Dimensions.get('window');

export const dS = StyleSheet.create({
  statsRow:    { flexDirection: 'row', marginHorizontal: 16, marginVertical: 12, gap: 8 },
  statBox:     { flex: 1, backgroundColor: C.bgSecondary, borderRadius: 10, padding: 10, alignItems: 'center', borderWidth: 0.5, borderColor: C.hairline },
  statBoxHi:   { borderColor: C.burgundy },
  statVal:     { fontFamily: F.en, fontSize: 22, color: C.charcoal, lineHeight: 26 },
  statLabel:   { fontFamily: F.sys, fontSize: 10, color: C.warmGrayLight, marginTop: 2 },
  tabStripeRow:       { flexDirection: 'row', height: 3, marginHorizontal: 16 },
  tabStripeSegment:   { flex: 1, opacity: 0.3, borderRadius: 2 },
  tabStripeSegmentOn: { opacity: 1, height: 5, marginTop: -1 },
  tabRow:      { flexDirection: 'row', marginHorizontal: 16, marginBottom: 4, marginTop: 2 },
  tabBtn:      { flex: 1, alignItems: 'center', paddingVertical: 8 },
  tabTxt:      { fontFamily: F.sys, fontSize: 13, color: C.warmGrayLight },
  tabTxtOn:    { color: C.charcoal, fontWeight: '600' },
  tlNode:      { paddingLeft: 24, position: 'relative', marginBottom: 10 },
  // 검색/필터
  filterRow:         { flexDirection: 'row', alignItems: 'center', borderBottomWidth: 0.5, borderBottomColor: '#E8E2D0' },
  filterTabRow:      { paddingLeft: 16 },
  filterTab:         { paddingHorizontal: 12, paddingVertical: 6, borderBottomWidth: 2, borderBottomColor: 'transparent' },
  filterTabOn:       { borderBottomColor: '#6B1E2A' },
  filterTabTxt:      { fontFamily: F.sys, fontSize: 11, color: '#8B8680' },
  filterTabTxtOn:    { color: '#3D3935', fontWeight: '700' },
  searchToggleBtn:   { paddingHorizontal: 14, paddingVertical: 6, borderLeftWidth: 0.5, borderLeftColor: '#E8E2D0' },
  searchToggleTxt:   { fontSize: 16 },
  searchWrap:        { flexDirection: 'row', alignItems: 'center', backgroundColor: '#fff', borderWidth: 0.5, borderColor: '#E8E2D0', borderRadius: 10, paddingHorizontal: 14, paddingVertical: 8, marginHorizontal: 16, marginVertical: 6 },
  searchIcon:        { fontSize: 14, marginRight: 8 },
  searchInput:       { flex: 1, fontFamily: F.sys, fontSize: 13, color: C.charcoal, padding: 0 },
  searchCloseTxt:    { fontSize: 14, color: C.warmGray, paddingHorizontal: 6 },
  emptyWrap:   { alignItems: 'center', paddingVertical: 60 },
  emptyMsg:    { fontFamily: F.sys, fontSize: 13, color: C.warmGrayLight },
  tlLine:      { position: 'absolute', left: 7, top: 14, bottom: -10, width: 1, backgroundColor: C.hairline },
  tlDot:       { position: 'absolute', left: 2, top: 10, width: 10, height: 10, borderRadius: 5, backgroundColor: C.bgPrimary, borderWidth: 1.5, borderColor: C.hairline },
  tlDotBest:   { backgroundColor: C.burgundy, borderColor: C.burgundy },
  tlDotBirdie: { backgroundColor: C.butter, borderColor: C.charcoal },
  tlDotSpecial:{ backgroundColor: '#C9A84C', borderColor: '#C9A84C', width: 12, height: 12, left: 1 },
  card:        { backgroundColor: '#fff', borderRadius: 14, overflow: 'hidden', borderWidth: 0.5, borderColor: '#E8E2D0' },
  cardSpecial:     { backgroundColor: '#F5F0E4', borderColor: '#C9A84C', borderWidth: 1 },
  cardSpecialLine: { height: 2, backgroundColor: '#C9A84C' },
  specialBadge:    { position: 'absolute', top: 9, left: 10, backgroundColor: 'rgba(201,168,76,0.9)', borderRadius: 5, paddingHorizontal: 8, paddingVertical: 3 },
  specialBadgeTxt: { fontFamily: F.sys, fontSize: 9, color: '#2A2622', letterSpacing: 0.5 },
  specialNoPhoto:  { backgroundColor: '#EDE8DC', padding: 16, alignItems: 'center', borderBottomWidth: 0.5, borderBottomColor: '#C9A84C33' },
  specialNoPhotoTxt: { fontFamily: F.en, fontSize: 16, color: '#8B6914', fontStyle: 'italic', letterSpacing: 2 },
  specialNoPhotoSub: { fontFamily: F.sys, fontSize: 11, color: '#B8A878', marginTop: 4 },
  hofSectionLabel: { fontFamily: F.sys, fontSize: 10, color: '#C9A84C', letterSpacing: 3 },
  hofToggle:   { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 10, paddingVertical: 4 },
  hofCard:     { backgroundColor: '#F5F0E4', borderRadius: 14, borderWidth: 1, borderColor: '#C9A84C', overflow: 'hidden', marginBottom: 12 },
  hofHeader:   { flexDirection: 'row', alignItems: 'center', padding: 14, paddingBottom: 10, borderBottomWidth: 0.5, borderBottomColor: '#C9A84C33' },
  hofType:     { fontFamily: F.en, fontSize: 15, color: '#8B6914', fontStyle: 'italic', letterSpacing: 2 },
  hofDate:     { fontFamily: F.sys, fontSize: 10, color: '#B8A878', marginTop: 2 },
  hofGoldDot:  { width: 8, height: 8, borderRadius: 4, backgroundColor: '#C9A84C' },
  hofGrid:     { flexDirection: 'row', flexWrap: 'wrap', padding: 10, gap: 6 },
  hofCell:     { width: '47%', backgroundColor: '#EDE8DC', borderRadius: 8, padding: 10, borderWidth: 0.5, borderColor: '#C9A84C33' },
  hofCellLabel:{ fontFamily: F.sys, fontSize: 7, color: '#B8A878', letterSpacing: 2, marginBottom: 4 },
  hofCellVal:  { fontFamily: F.sys, fontSize: 10, color: '#3D3935', lineHeight: 15 },
  hofCellBig:  { fontFamily: F.en, fontSize: 24, color: '#C9A84C', lineHeight: 28 },
  hofDivider:  { height: 0.5, backgroundColor: '#C9A84C33', marginHorizontal: 14 },
  hofMemo:     { fontFamily: F.en, fontSize: 11, color: '#6B6660', fontStyle: 'italic', padding: 14, lineHeight: 18 },
  specialBanner:    { padding: 24, alignItems: 'center' },
  specialBannerTitle: { fontFamily: F.en, fontSize: 34, color: '#C9A84C', fontStyle: 'italic', letterSpacing: 5, marginVertical: 6 },
  specialBannerSub:   { fontFamily: F.sys, fontSize: 9, color: 'rgba(201,168,76,0.6)', letterSpacing: 4 },
  photoHero43:        { width: '100%', aspectRatio: 4/3, position: 'relative' },
  photoImg:           { width: '100%', height: '100%' },
  photoBottomOverlay: { position: 'absolute', left: 0, right: 0, bottom: 0, height: 50, backgroundColor: 'rgba(0,0,0,0.2)', justifyContent: 'flex-end', padding: 10 },
  overlayCourse:      { fontFamily: F.sys, fontSize: 13, color: '#fff', fontWeight: '600', textShadowColor: 'rgba(0,0,0,0.9)', textShadowOffset: { width: 0, height: 2 }, textShadowRadius: 6 },
  overlayDate:        { fontFamily: F.sys, fontSize: 10, color: 'rgba(255,255,255,0.7)', marginTop: 2, textShadowColor: 'rgba(0,0,0,0.9)', textShadowOffset: { width: 0, height: 1 }, textShadowRadius: 4 },
  toggleBtn:          { paddingVertical: 9, borderTopWidth: 0.5, borderTopColor: '#F0EAD8', backgroundColor: '#FDFAF5', alignItems: 'center' },
  toggleBtnTxt:       { fontFamily: F.sys, fontSize: 11, color: '#8B8680' },
  photoCount:         { position: 'absolute', bottom: 8, right: 10, backgroundColor: 'rgba(0,0,0,0.45)', borderRadius: 10, paddingHorizontal: 8, paddingVertical: 2 },
  photoCountTxt:      { fontFamily: F.sys, fontSize: 10, color: 'rgba(255,255,255,0.9)' },
  cardBody:    { padding: 12 },
  cardDate:    { fontFamily: F.sys, fontSize: 10, color: C.warmGrayLight, marginBottom: 4 },
  cardCourse:  { fontFamily: F.sys, fontSize: 13, color: C.textPrimary, marginBottom: 8 },
  cardScore:   { fontFamily: F.en, fontSize: 24, color: C.charcoal, lineHeight: 28 },
  cardScoreUnit: { fontFamily: F.sys, fontSize: 14, color: C.charcoal },
  cardPar:     { fontFamily: F.sys, fontSize: 10, color: C.warmGrayLight, marginTop: 2 },
  detailHdr:      { backgroundColor: C.bgPrimary, paddingHorizontal: 16, paddingTop: 12, paddingBottom: 8, borderBottomWidth: 0.5, borderBottomColor: C.hairline, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  backBtn:        { fontFamily: F.sys, fontSize: 13, color: C.warmGrayLight },
  detailHdrNickname:    { backgroundColor: '#6B1E2A', borderRadius: 16, paddingHorizontal: 12, paddingVertical: 5 },
  detailHdrNicknameTxt: { fontFamily: F.sys, fontSize: 12, color: '#F5E6A8', fontWeight: '600' },
  detailInfoArea:  { padding: 16, borderBottomWidth: 0.5, borderBottomColor: C.hairline },
  detailScoreRow:  { flexDirection: 'row', alignItems: 'baseline', gap: 8, flexWrap: 'wrap', marginBottom: 4 },
  detailScore:     { fontFamily: F.en, fontSize: 48, color: C.charcoal, lineHeight: 54 },
  detailScoreUnit: { fontFamily: F.en, fontSize: 20, color: C.charcoal },
  detailScoreSub:  { fontFamily: F.sys, fontSize: 12, color: C.warmGrayLight },
  detailCourseTxt: { fontFamily: F.sys, fontSize: 12, color: C.warmGrayLight, marginBottom: 12 },
  detailMemoBox:   { borderLeftWidth: 2, borderLeftColor: C.burgundy, paddingLeft: 10, marginBottom: 14 },
  detailMemoTxt:   { fontFamily: F.en, fontSize: 14, color: C.textPrimary, fontStyle: 'italic', lineHeight: 22 },
  companionArea:       { flexDirection: 'row', alignItems: 'flex-start', gap: 10 },
  companionLabel:      { fontFamily: F.sys, fontSize: 10, color: C.warmGrayLight, letterSpacing: 1, marginTop: 9 },
  avatarLine:          { flexDirection: 'row', alignItems: 'center', gap: 10 },
  avatarRow:           { flexDirection: 'row', alignItems: 'center' },
  avatar:              { width: 32, height: 32, borderRadius: 16, borderWidth: 2, borderColor: '#FAF6EC', alignItems: 'center', justifyContent: 'center' },
  avatarTxt:           { fontFamily: F.sys, fontSize: 13, fontWeight: '600' },
  compNames:           { fontFamily: F.sys, fontSize: 11, color: '#8B8680', flex: 1 },
  photosArea:      { padding: 16 },
  photosLabel:     { fontFamily: F.sys, fontSize: 10, color: C.warmGrayLight, letterSpacing: 1.5 },
  photosGrid:      { flexDirection: 'row', flexWrap: 'wrap', gap: 6 },
  photoGridItem:   { width: (SW - 38) / 2, height: (SW - 38) / 2, borderRadius: 10, overflow: 'hidden' },
  photoGridImg:    { width: '100%', height: '100%' },
  banner:      { marginHorizontal: 16, marginVertical: 10, backgroundColor: C.butter + '22', borderWidth: 0.5, borderColor: C.butter, borderRadius: 10, padding: 12 },
  bannerTitle: { fontFamily: F.sys, fontSize: 13, color: C.textPrimary, marginBottom: 2 },
  bannerSub:   { fontFamily: F.sys, fontSize: 11, color: C.burgundy },
  courseCard:  { marginHorizontal: 16, marginBottom: 10, backgroundColor: C.bgSecondary, borderRadius: 12, padding: 14, borderWidth: 0.5, borderColor: C.hairline },
  courseName:  { fontFamily: F.sys, fontSize: 13, color: C.textPrimary, flex: 1 },
  courseLoc:   { fontFamily: F.sys, fontSize: 11, color: C.warmGrayLight, marginBottom: 8 },
  tag:         { backgroundColor: C.butter + '44', borderRadius: 5, paddingHorizontal: 7, paddingVertical: 2 },
  tagTxt:      { fontFamily: F.sys, fontSize: 10, color: C.charcoal },
  recordRow:   { flexDirection: 'row', gap: 6, marginBottom: 10 },
  recVisit:    { flex: 1, backgroundColor: C.bgSecondary, borderRadius: 8, padding: 8, alignItems: 'center', borderWidth: 0.5, borderColor: C.hairline },
  recBest:     { flex: 1, backgroundColor: C.burgundy, borderRadius: 8, padding: 8, alignItems: 'center' },
  recAvg:      { flex: 1, backgroundColor: C.butter + '30', borderRadius: 8, padding: 8, alignItems: 'center', borderWidth: 0.5, borderColor: C.butter },
  recValDark:  { fontFamily: F.en, fontSize: 20, color: C.charcoal, lineHeight: 24 },
  recValWhite: { fontFamily: F.en, fontSize: 20, color: '#fff', lineHeight: 24 },
  recValButter:{ fontFamily: F.en, fontSize: 20, color: '#6B5500', lineHeight: 24 },
  recLblDark:  { fontFamily: F.sys, fontSize: 9, color: C.warmGrayLight, marginTop: 2 },
  recLblWhite: { fontFamily: F.sys, fontSize: 9, color: 'rgba(255,255,255,0.6)', marginTop: 2 },
  recLblButter:{ fontFamily: F.sys, fontSize: 9, color: '#8B7000', marginTop: 2 },
  courseMemo:  { fontFamily: F.en, fontSize: 11, color: C.textSecondary, fontStyle: 'italic', borderLeftWidth: 1.5, borderLeftColor: C.burgundy, paddingLeft: 8 },
});
