import { StyleSheet } from 'react-native';
import { C, F } from '../constants/colors';

export const gS = StyleSheet.create({
  searchTxt:       { fontFamily: F.en, fontSize: 15, color: C.charcoal, fontStyle: 'italic', borderBottomWidth: 0.5, borderBottomColor: C.charcoal, paddingBottom: 1 },
  chip:            { borderRadius: 20, paddingHorizontal: 12, paddingVertical: 5, backgroundColor: C.bgSecondary, borderWidth: 0.5, borderColor: C.hairline, height: 32, justifyContent: 'center' },
  chipOn:          { backgroundColor: C.charcoal },
  chipTxt:         { fontFamily: F.sys, fontSize: 12, color: C.warmGray },
  chipTxtOn:       { color: C.butter },
  courseCard:      { backgroundColor: C.bgSecondary, borderRadius: 12, padding: 14, marginBottom: 10, borderWidth: 0.5, borderColor: C.hairline },
  courseCardTop:   { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 4 },
  courseCardName:  { fontFamily: F.sys, fontSize: 13, color: C.textPrimary, flex: 1 },
  courseCardLoc:   { fontFamily: F.sys, fontSize: 11, color: C.warmGrayLight, marginBottom: 8 },
  courseCardScore: { fontFamily: F.sys, fontSize: 11, color: C.burgundy },
  courseCardArrow: { fontFamily: F.en, fontSize: 18, color: C.warmGrayLight },
  detailHdr:       { backgroundColor: C.bgPrimary, paddingHorizontal: 16, paddingTop: 12, paddingBottom: 0 },
  backBtn:         { fontFamily: F.sys, fontSize: 11, color: C.warmGrayLight, marginBottom: 6 },
  detailName:      { fontFamily: F.en, fontSize: 18, color: C.charcoal, fontStyle: 'italic', marginBottom: 2 },
  detailLoc:       { fontFamily: F.sys, fontSize: 11, color: C.warmGrayLight, marginBottom: 10 },
  favBtn:          { borderWidth: 1, borderColor: C.burgundy, borderRadius: 12, paddingHorizontal: 12, paddingVertical: 5, marginTop: 2, backgroundColor: C.burgundy },
  favBtnOn:        { backgroundColor: 'transparent', borderColor: C.warmGrayLight },
  favBtnTxt:       { fontFamily: F.sys, fontSize: 11, color: '#fff' },
  favBtnTxtOn:     { color: C.warmGrayLight },
  innerTab:        { flex: 1, alignItems: 'center', paddingBottom: 8 },
  innerTabTxt:     { fontFamily: F.sys, fontSize: 12, color: C.warmGrayLight },
  innerTabTxtOn:   { color: C.charcoal },
  secLabel:        { fontFamily: F.sys, fontSize: 12, color: C.charcoal, fontWeight: '700', letterSpacing: 1.5, marginBottom: 8 },
  infoCard:        { backgroundColor: C.bgSecondary, borderRadius: 10, padding: 14, borderWidth: 0.5, borderColor: C.hairline, marginBottom: 8 },
  infoRow:         { flexDirection: 'row', justifyContent: 'space-between', paddingVertical: 8, borderBottomWidth: 0.5, borderBottomColor: C.hairline },
  infoKey:         { fontFamily: F.sys, fontSize: 12, color: C.warmGrayLight },
  infoVal:         { fontFamily: F.sys, fontSize: 12, color: C.textPrimary },
  pill:            { borderRadius: 5, paddingHorizontal: 8, paddingVertical: 3 },
  pillTxt:         { fontFamily: F.sys, fontSize: 10, color: C.charcoal },
  memoBox:         { marginTop: 14, borderLeftWidth: 1.5, borderLeftColor: C.burgundy, paddingLeft: 10 },
  memoTxt:         { fontFamily: F.en, fontSize: 12, color: C.textSecondary, fontStyle: 'italic', lineHeight: 18 },
  restItem:        { backgroundColor: C.bgSecondary, borderRadius: 10, padding: 10, flexDirection: 'row', gap: 10, marginBottom: 8, borderWidth: 0.5, borderColor: C.hairline },
  restIcon:        { width: 38, height: 38, borderRadius: 8, alignItems: 'center', justifyContent: 'center' },
  mineBadge:       { backgroundColor: C.charcoal, borderRadius: 4, paddingHorizontal: 6, paddingVertical: 1, alignSelf: 'flex-start', marginBottom: 3 },
  mineBadgeTxt:    { fontFamily: F.sys, fontSize: 8, color: C.butter },
  restName:        { fontFamily: F.sys, fontSize: 12, color: C.textPrimary, marginBottom: 1 },
  restType:        { fontFamily: F.sys, fontSize: 10, color: C.warmGrayLight },
  restMemo:        { fontFamily: F.en, fontSize: 10, color: C.textSecondary, fontStyle: 'italic', marginTop: 3 },
  ratingBox:       { backgroundColor: C.butter, borderRadius: 6, paddingHorizontal: 7, paddingVertical: 3, alignSelf: 'center' },
  ratingTxt:       { fontFamily: F.sys, fontSize: 11, color: C.charcoal },
  commentCard:     { backgroundColor: C.bgSecondary, borderRadius: 10, padding: 12, marginBottom: 8, borderWidth: 0.5, borderColor: C.hairline },
  commentTxt:      { fontFamily: F.sys, fontSize: 13, color: '#3D3935', fontWeight: '400', lineHeight: 20 },
  commentWho:      { fontFamily: F.sys, fontSize: 10, color: C.warmGrayLight },
  commentAddBtn:   { borderWidth: 0.5, borderColor: C.hairline, borderRadius: 10, padding: 12, alignItems: 'center', marginTop: 4 },
  commentAddTxt:   { fontFamily: F.sys, fontSize: 12, color: C.warmGrayLight },
  nearbyCard:      { backgroundColor: C.bgSecondary, borderRadius: 10, padding: 12, flexDirection: 'row', alignItems: 'center', gap: 10, marginBottom: 8, borderWidth: 0.5, borderColor: C.hairline },
  nearbyIconWrap:  { width: 36, height: 36, borderRadius: 8, backgroundColor: C.bgPrimary, alignItems: 'center', justifyContent: 'center' },
  nearbyName:      { fontFamily: F.sys, fontSize: 12, color: C.textPrimary },
  nearbyLoc:       { fontFamily: F.sys, fontSize: 10, color: C.warmGrayLight, marginTop: 2 },
  nearbyDist:      { fontFamily: F.sys, fontSize: 11, color: C.burgundy },
  visitedBadge:    { backgroundColor: C.butter + '66', borderRadius: 4, paddingHorizontal: 5, paddingVertical: 1 },
  visitedBadgeTxt: { fontFamily: F.sys, fontSize: 8, color: C.charcoal },
  emptyBanner:     { margin: 16, backgroundColor: C.paleSky + '30', borderWidth: 0.5, borderColor: C.paleSky, borderRadius: 12, padding: 20, alignItems: 'center' },
  emptyTitle:      { fontFamily: F.en, fontSize: 16, color: C.charcoal, fontStyle: 'italic', marginBottom: 8 },
  emptySub:        { fontFamily: F.sys, fontSize: 12, color: C.warmGrayLight, textAlign: 'center', lineHeight: 18 },
});
