import { StyleSheet } from 'react-native';
import { C, F, fs } from '../constants/colors';

export const gS = StyleSheet.create({
  searchTxt:       { fontFamily: F.en, fontSize: fs(15), color: C.charcoal, borderBottomWidth: 0.5, borderBottomColor: C.charcoal, paddingBottom: 1 },
  chip:            { borderRadius: 20, paddingHorizontal: 12, paddingVertical: 5, backgroundColor: C.bgSecondary, borderWidth: 0.5, borderColor: C.hairline, height: 32, justifyContent: 'center' },
  chipOn:          { backgroundColor: C.charcoal },
  chipTxt:         { fontFamily: F.sys, fontSize: fs(12), color: C.warmGray },
  chipTxtOn:       { color: C.butter },
  courseCard:      { backgroundColor: C.bgSecondary, borderRadius: 12, padding: 14, marginBottom: 10, borderWidth: 0.5, borderColor: C.hairline },
  courseCardTop:   { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 4 },
  courseCardName:  { fontFamily: F.sys, fontSize: fs(13), color: C.textPrimary, flex: 1 },
  courseCardLoc:   { fontFamily: F.sys, fontSize: fs(11), color: C.warmGray, marginBottom: 8 },
  courseCardScore: { fontFamily: F.sys, fontSize: fs(11), color: C.burgundy },
  courseCardArrow: { fontFamily: F.en, fontSize: fs(18), color: C.warmGray },
  detailHdr:       { backgroundColor: C.bgPrimary, paddingHorizontal: 16, paddingTop: 12, paddingBottom: 0 },
  backBtn:         { fontFamily: F.sys, fontSize: fs(11), color: C.warmGray, marginBottom: 6 },
  detailName:      { fontFamily: F.en, fontSize: fs(18), color: C.charcoal, marginBottom: 2 },
  detailLoc:       { fontFamily: F.sys, fontSize: fs(11), color: C.warmGray, marginBottom: 10 },
  favBtn:          { borderWidth: 1, borderColor: C.burgundy, borderRadius: 12, paddingHorizontal: 12, paddingVertical: 5, marginTop: 2, backgroundColor: C.burgundy },
  favBtnOn:        { backgroundColor: 'transparent', borderColor: C.warmGrayLight },
  favBtnTxt:       { fontFamily: F.sys, fontSize: fs(11), color: '#fff' },
  favBtnTxtOn:     { color: C.warmGray },
  innerTab:        { flex: 1, alignItems: 'center', paddingBottom: 8 },
  innerTabTxt:     { fontFamily: F.sys, fontSize: fs(12), color: C.warmGray },
  innerTabTxtOn:   { color: C.charcoal },
  secLabel:        { fontFamily: F.sysB, fontSize: fs(12), color: C.charcoal, letterSpacing: 1.5, marginBottom: 8 },
  infoCard:        { backgroundColor: C.bgSecondary, borderRadius: 10, padding: 14, borderWidth: 0.5, borderColor: C.hairline, marginBottom: 8 },
  infoRow:         { flexDirection: 'row', justifyContent: 'space-between', paddingVertical: 8, borderBottomWidth: 0.5, borderBottomColor: C.hairline },
  infoKey:         { fontFamily: F.sys, fontSize: fs(12), color: C.warmGray },
  infoVal:         { fontFamily: F.sys, fontSize: fs(12), color: C.textPrimary },
  pill:            { borderRadius: 5, paddingHorizontal: 8, paddingVertical: 3 },
  pillTxt:         { fontFamily: F.sys, fontSize: fs(10), color: C.charcoal },
  memoBox:         { marginTop: 14, borderLeftWidth: 1.5, borderLeftColor: C.burgundy, paddingLeft: 10 },
  memoTxt:         { fontFamily: F.en, fontSize: fs(12), color: C.textSecondary, lineHeight: 18 },
  restItem:        { backgroundColor: C.bgSecondary, borderRadius: 10, padding: 10, flexDirection: 'row', gap: 10, marginBottom: 8, borderWidth: 0.5, borderColor: C.hairline },
  restIcon:        { width: 38, height: 38, borderRadius: 8, alignItems: 'center', justifyContent: 'center' },
  restName:        { fontFamily: F.sys, fontSize: fs(12), color: C.textPrimary, marginBottom: 1 },
  restType:        { fontFamily: F.sys, fontSize: fs(10), color: C.warmGray },
  restMemo:        { fontFamily: F.en, fontSize: fs(10), color: C.textSecondary, marginTop: 3 },
  ratingBox:       { backgroundColor: C.butter, borderRadius: 6, paddingHorizontal: 7, paddingVertical: 3, alignSelf: 'center' },
  ratingTxt:       { fontFamily: F.sys, fontSize: fs(11), color: C.charcoal },
  // 골퍼 코멘트 섹션 — 박스 X. 전체폭 색띠(색구분만)로 게시판 영역 표시 (2026-06-01)
  //   marginHorizontal:-16 으로 부모 padding(16) 상쇄 → 화면 끝까지, paddingHorizontal:16 으로 내용 인셋 복원, borderRadius 없음
  commentPanel:    { backgroundColor: '#F6EFD9', marginHorizontal: -16, paddingHorizontal: 16, paddingTop: 16, paddingBottom: 10, marginTop: 18, marginBottom: 18 },
  commentCard:     { backgroundColor: C.bgSecondary, borderRadius: 10, padding: 12, marginBottom: 8, borderWidth: 0.5, borderColor: C.hairline },
  // 내 코멘트 — 버건디 좌측 액센트로 한눈에 구분
  commentCardMine: { borderLeftWidth: 3, borderLeftColor: C.burgundy },
  // ★위 맛집 블록에 같은 이름(차콜·fs8)이 한 번 더 있었다 — 뒤엣것이 이기므로 실제로 그려진 건 늘 이 버건디였고,
  //   앞 정의는 죽은 코드였다. 08-04 ESLint(no-dupe-keys)로 발견해 삭제. 표시는 그대로다.
  mineBadge:       { backgroundColor: C.burgundy, borderRadius: 5, paddingHorizontal: 6, paddingVertical: 1 },
  mineBadgeTxt:    { fontFamily: F.sysB, fontSize: fs(11), color: C.butter },
  // 한줄 메모 헤더 우측 '내 기록 N회' 칩
  mineCountPill:   { backgroundColor: 'rgba(107,30,42,0.07)', borderRadius: 8, paddingHorizontal: 9, paddingVertical: 3 },
  mineCountTxt:    { fontFamily: F.sysSb, fontSize: fs(11), color: C.burgundy },
  commentTxt:      { fontFamily: F.sys, fontSize: fs(13), color: '#3D3935', lineHeight: 20 },
  commentWho:      { fontFamily: F.sys, fontSize: fs(10), color: C.warmGray },
  commentAddBtn:   { borderWidth: 0.5, borderColor: C.hairline, borderRadius: 10, padding: 12, alignItems: 'center', marginTop: 4 },
  commentAddTxt:   { fontFamily: F.sys, fontSize: fs(12), color: C.warmGray },
  nearbyCard:      { backgroundColor: C.bgSecondary, borderRadius: 10, padding: 12, flexDirection: 'row', alignItems: 'center', gap: 10, marginBottom: 8, borderWidth: 0.5, borderColor: C.hairline },
  nearbyIconWrap:  { width: 36, height: 36, borderRadius: 8, backgroundColor: C.bgPrimary, alignItems: 'center', justifyContent: 'center' },
  nearbyName:      { fontFamily: F.sys, fontSize: fs(12), color: C.textPrimary },
  nearbyLoc:       { fontFamily: F.sys, fontSize: fs(10), color: C.warmGray, marginTop: 2 },
  nearbyDist:      { fontFamily: F.sys, fontSize: fs(11), color: C.burgundy },
  visitedBadge:    { backgroundColor: C.butter + '66', borderRadius: 4, paddingHorizontal: 5, paddingVertical: 1 },
  visitedBadgeTxt: { fontFamily: F.sys, fontSize: fs(8), color: C.charcoal },
  emptyBanner:     { margin: 16, backgroundColor: C.paleSky + '30', borderWidth: 0.5, borderColor: C.paleSky, borderRadius: 12, padding: 20, alignItems: 'center' },
  emptyTitle:      { fontFamily: F.en, fontSize: fs(16), color: C.charcoal, fontStyle: 'italic', marginBottom: 8 },
  emptySub:        { fontFamily: F.sys, fontSize: fs(12), color: C.warmGray, textAlign: 'center', lineHeight: 18 },
});
